### ISSUE TITLE
DLS issue in Kibana Index configure

### ISSUE THREAD

**Issue by yasvanth** [floragunncom/search-guard-module-dlsfls#4]
Hi,
Setup:
ES : 5.2 SG -v5-12 and new DLS is enabled .
One node for elasticsearch and one for logstash and kibana. 

After enabling DLS for one user I couldn't configure the index on kibana end.

My DLS configuration is:
<pre>
sg_user_apache:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '*':
      '*':
        - '*'
      _dls_: '{ "term" : {"LogType" : "apache_Logs"} }'
    '?kibana*':
      '*':
        - '*'
      _dls_: '{ "term" : {"LogType" : "apache_Logs"} }'

</pre>

when I configure the index on kibana in management. I get blow error:
<pre>
Could not locate that index-pattern (id: logs-*) 
</pre>
But the index is exists and can be configured from other user accounts 
<pre>
Config: Error 404 Not Found: [document_missing_exception] [config][5.2.2]: document missing, with { index_uuid="iHz9NI1ySdKONSEadGzy_A" & shard="0" & index=".kibana" }
</pre>

DLS user is recently enabled for user apache, before DLS this user works fine.

There is no issues for other users which DLS is not enabled.

Thanks,
Yash

**Comment by floragunncom** [comment]
That's not related to DLSFLS, but a bug in the multi tenancy module. It's tracked here:

https://github.com/floragunncom/search-guard-module-kibana-multitenancy/issues/8

Fixed version will be released soon.

See also:

https://groups.google.com/forum/#!topic/search-guard/kh7E1Oh5xro

**Comment by yasvanth** [comment]
oh, Will the fix will be available in next kibana release?
Thanks,
Yash

**Comment by floragunncom** [comment]
In the next release of the Kibana multitenancy module. For a quick fix, please refer to the Google Groups article.

**Comment by yasvanth** [comment]
After this  I tried with ES-5.3 and DLS module 5.3-6 ( 3 node cluster 1 (kiba/logstash) 1 master-es and 1 data-es nodes ) 
but when I run sgadmin.sh dosen't show 
<pre>
Searchguard DLS/FLS(+) Security is not free software
for commercial use in production.
You have to obtain a license if you
use it in production.
(+) Document-/Fieldlevel
</pre>

I check the logs I got this error 
<pre>
[2017-06-08T14:52:01,176][INFO ][c.f.s.SearchGuardPlugin  ] FLS/DLS valve bound
</pre>
